<a href="https://colab.research.google.com/github/IndraniMandal/DSP-292X/blob/master/DSA_202_Week_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Pipeline
Data pipeline defines the work flow of data processing. 

## Data source
Data come from various souces like Analytics data (user behavior data), Transactional data (data from sales and product records), 3rd party data, government data, data from web scrapping, etc. 

## Data Ingestion/Collection
The data is then integrated from these different sources and entering it into the data pipeline. 

## Data processing 
The processing layer transforms the data into a consumable state. This process involves data validation, clean-up, normalization, transformation, and enrichment.

![Data pipeline.png]()

Picture credit: [A Guide to Data Pipelines](https://www.striim.com/blog/guide-to-data-pipelines/)

## Data Consumption
The data is now ready for comsumption for advanced analytics and machine learning. We make sense of the data by visualizing the data and performing exploratory analysis. We can perform predictive analytics by building models. Models learn from the data provided and can be used for making predictions about the unknown.

# Machine Learning Pipeline
In this phase we train the model using the data we have collected and test the model performance.

![machine-learning-pipeline.png]()

Picture credit: [Machine learning Pipeline Deployment and Architecture](https://www.xenonstack.com/blog/machine-learning-pipeline)

## Load the Data

### Connecting to my Github

In [ ]:
!test -e ds-assets && cd ds-assets && git pull && cd ..
!test ! -e ds-assets && git clone https://github.com/IndraniMandal/ds-assets.git
home = "ds-assets/assets/" 
import sys
sys.path.append(home)

Already up to date.

You can direct access the notebooks my Github. You can access data from there or any other resources shared there.

###Loading data from local drive
I have this dataset on Pancreatic cancer saved in my local drive. You can find more information on the [dataset here](
https://www.kaggle.com/datasets/johnjdavisiv/urinary-biomarkers-for-pancreatic-cancer).

In [1]:
from google.colab import files
import io

In [5]:
uploaded = files.upload()

Saving Pancreatic Cancer 2020.csv to Pancreatic Cancer 2020.csv

Instantiates the uploaded file as a readable csv link

In [6]:
uploaded = io.BytesIO(uploaded['Pancreatic Cancer 2020.csv'])

Convert the uploaded file into a readable dataframe. Dataframes refresent the uploaded file into a tabular format and offer function operations on them.

In [7]:
import pandas as pd
cancer_df = pd.read_csv(uploaded)
cancer_df.head()

,sample_id,patient_cohort,sample_origin,age,sex,diagnosis,stage,benign_sample_diagnosis,plasma_CA19_9,creatinine,LYVE1,REG1B,TFF1,REG1A
0,S1,Cohort1,BPTB,33,F,1,NaN,NaN,11.7,1.83222,0.893219,52.94884,654.282174,1262.000
1,S10,Cohort1,BPTB,81,F,1,NaN,NaN,NaN,0.97266,2.037585,94.46703,209.488250,228.407
2,S100,Cohort2,BPTB,51,M,1,NaN,NaN,7.0,0.78039,0.145589,102.36600,461.141000,NaN
3,S101,Cohort2,BPTB,61,M,1,NaN,NaN,8.0,0.70122,0.002805,60.57900,142.950000,NaN
4,S102,Cohort2,BPTB,62,M,1,NaN,NaN,9.0,0.21489,0.000860,65.54000,41.088000,NaN

### Loding data from Github

You can directly access data stored in a Github Repo. This is more efficent than directly uploading file from local. Additionally, sharing data and notebooks are much eaiser through Github repos.

Always access the Raw file from Github. If you use link to Github's rendering of the dataset you will get an error.

In [10]:
url = "https://raw.githubusercontent.com/IndraniMandal/ds-assets/main/assets/abalone.csv"
df = pd.read_csv(url)
df.head()

,sex,length,diameter,height,whole weight,shucked weight,viscera weight,shell weight
0,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210
1,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055
2,I,0.425,0.300,0.095,0.3515,0.1410,0.0775,0.120
3,F,0.530,0.415,0.150,0.7775,0.2370,0.1415,0.330
4,F,0.545,0.425,0.125,0.7680,0.2940,0.1495,0.260

### Loaing data from Google Drive for colabs

You can access datasets saved in a Google drive from Google Colab. You have to give permission to Google Colab to access your Google drive.

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
gdrive = pd.read_csv("/content/drive/MyDrive/Datasets/wdbc.csv")
gdrive.head()

,ID,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,...,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3,Diagnosis
0,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,M
1,2,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,M
2,3,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,M
3,4,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,M
4,5,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,M

###Kaggle
####Local drive set up and implementation

We can upload data from Kaggle.com as well. You can use linux based commands to install necessary library, make directory and assign necessary permissions. It requires uploading the kaggle.json file to the notebook on restart.

kaggle.json files are obtained from Kaggle.com under user settings.

In [9]:
! pip install kaggle
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.8/dist-packages (1.5.12)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.8/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.8/dist-packages (from kaggle) (7.0.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.8/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.8/dist-packages (from kaggle) (2022.12.7)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from kaggle) (2.25.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from kaggle) (4.64.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.8/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle) (4.0.0)
mkdir: cannot create directory ‘/root/.kaggle’: File exists
cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory

Downloads the dataset straight from the source in Kaggle as a zip file

In [10]:
! kaggle datasets download johnjdavisiv/urinary-biomarkers-for-pancreatic-cancer

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 5, in <module>
    from kaggle.cli import main
  File "/usr/local/lib/python3.8/dist-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/usr/local/lib/python3.8/dist-packages/kaggle/api/kaggle_api_extended.py", line 164, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.

Unzips the Kaggle file and deletes the zip file (doesn't need to delete it, I just find it to be in the way)

Might be a better example if using a different Kaggle dataset

In [11]:
!unzip /content/urinary-biomarkers-for-pancreatic-cancer.zip
!rm /content/urinary-biomarkers-for-pancreatic-cancer.zip

unzip:  cannot find or open /content/urinary-biomarkers-for-pancreatic-cancer.zip, /content/urinary-biomarkers-for-pancreatic-cancer.zip.zip or /content/urinary-biomarkers-for-pancreatic-cancer.zip.ZIP.
rm: cannot remove '/content/urinary-biomarkers-for-pancreatic-cancer.zip': No such file or directory

####Google drive set up and implementation
The same process for the previously mentioned Kaggle method can be applied but this time in your google drive. The kaggle.json file can be saved in your Google drive.

In [12]:
! pip install kaggle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.8/dist-packages (1.5.12)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.8/dist-packages (from kaggle) (7.0.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.8/dist-packages (from kaggle) (2022.12.7)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from kaggle) (4.64.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from kaggle) (2.25.1)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.8/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.8/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.8/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle) (2.10)

In [17]:
! mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists

In [18]:
!cp /content/drive/MyDrive/kaggle.json ~/.kaggle/kaggle.json

Downloads the dataset straight from the source in Kaggle as a zip file

In [19]:
! kaggle datasets download johnjdavisiv/urinary-biomarkers-for-pancreatic-cancer

Downloading urinary-biomarkers-for-pancreatic-cancer.zip to /content
  0% 0.00/18.0k [00:00<?, ?B/s]
100% 18.0k/18.0k [00:00<00:00, 14.5MB/s]

Unzips the Kaggle file and deletes the zip file (doesn't need to delete it, I just find it to be in the way)

In [20]:
!unzip /content/urinary-biomarkers-for-pancreatic-cancer.zip
!rm /content/urinary-biomarkers-for-pancreatic-cancer.zip

Archive:  /content/urinary-biomarkers-for-pancreatic-cancer.zip
  inflating: Debernardi et al 2020 data.csv
  inflating: Debernardi et al 2020 documentation.csv

Displays the csv obtained from Kaggle

In [21]:
import pandas as pd
kaggle = pd.read_csv("/content/Debernardi et al 2020 data.csv")
kaggle.head()

,sample_id,patient_cohort,sample_origin,age,sex,diagnosis,stage,benign_sample_diagnosis,plasma_CA19_9,creatinine,LYVE1,REG1B,TFF1,REG1A
0,S1,Cohort1,BPTB,33,F,1,NaN,NaN,11.7,1.83222,0.893219,52.94884,654.282174,1262.000
1,S10,Cohort1,BPTB,81,F,1,NaN,NaN,NaN,0.97266,2.037585,94.46703,209.488250,228.407
2,S100,Cohort2,BPTB,51,M,1,NaN,NaN,7.0,0.78039,0.145589,102.36600,461.141000,NaN
3,S101,Cohort2,BPTB,61,M,1,NaN,NaN,8.0,0.70122,0.002805,60.57900,142.950000,NaN
4,S102,Cohort2,BPTB,62,M,1,NaN,NaN,9.0,0.21489,0.000860,65.54000,41.088000,NaN

# Urinary biomarkers for pancreatic cancer Dataset
### About Dataset
This is a [dataset](https://www.kaggle.com/datasets/johnjdavisiv/urinary-biomarkers-for-pancreatic-cancer?resource=download) from an open-access paper published December 10, 2020. The paper and the full dataset are open-access (CC-BY), so please give attribution to the original authors in your work.

###Background
Pancreatic cancer is an extremely deadly type of cancer. Once diagnosed, the five-year survival rate is less than 10%. However, if pancreatic cancer is caught early, the odds of surviving are much better. Unfortunately, many cases of pancreatic cancer show no symptoms until the cancer has spread throughout the body. A diagnostic test to identify people with pancreatic cancer could be enormously helpful.

###Background
Pancreatic cancer is an extremely deadly type of cancer. Once diagnosed, the five-year survival rate is less than 10%. However, if pancreatic cancer is caught early, the odds of surviving are much better. Unfortunately, many cases of pancreatic cancer show no symptoms until the cancer has spread throughout the body. A diagnostic test to identify people with pancreatic cancer could be enormously helpful.

###The paper
In a paper by Silvana Debernardi and colleagues, published this year in the journal PLOS Medicine, a multi-national team of researchers sought to develop an accurate diagnostic test for the most common type of pancreatic cancer, called pancreatic ductal adenocarcinoma or PDAC. They gathered a series of biomarkers from the urine of three groups of patients:

###Healthy controls
* Patients with non-cancerous pancreatic conditions, like chronic pancreatitis
* Patients with pancreatic ductal adenocarcinoma

When possible, these patients were age- and sex-matched. The goal was to develop an accurate way to identify patients with pancreatic cancer.

###The data
The key features are four urinary biomarkers: creatinine, LYVE1, REG1B, and TFF1.

* Creatinine is a protein that is often used as an indicator of kidney function.
* YVLE1 is lymphatic vessel endothelial hyaluronan receptor 1, a protein that may play a role in tumor metastasis
* REG1B is a protein that may be associated with pancreas regeneration
* TFF1 is trefoil factor 1, which may be related to regeneration and repair of the urinary tract

**Age** and **sex**, both included in the dataset, may also play a role in who gets pancreatic cancer. The dataset includes a few other biomarkers as well, but these were not measured in all patients (they were collected partly to measure how various blood biomarkers compared to urine biomarkers).

I have not changed any of the data from the paper, other than renaming the columns for easy importing and use. The file *Debernardi et al 2020 data.csv* contains the raw data, while the file *Debernardi et al 2020 documentation.csv *contains a detailed documentation of what each column represents (as well as the original column names from the paper).

###Prediction task
The goal in this dataset is predicting diagnosis, and more specifically, differentiating between 3 (pancreatic cancer) versus 2 (non-cancerous pancreas condition) and 1 (healthy). The dataset includes information on stage of pancreatic cancer, and diagnosis for non-cancerous patients, but remember—these won't be available to a predictive model. The goal, after all, is to predict the presence of disease before it's diagnosed, not after!

##Load the Data from Kaggle

In [22]:
kaggle = pd.read_csv("/content/Debernardi et al 2020 data.csv")
kaggle.head()

,sample_id,patient_cohort,sample_origin,age,sex,diagnosis,stage,benign_sample_diagnosis,plasma_CA19_9,creatinine,LYVE1,REG1B,TFF1,REG1A
0,S1,Cohort1,BPTB,33,F,1,NaN,NaN,11.7,1.83222,0.893219,52.94884,654.282174,1262.000
1,S10,Cohort1,BPTB,81,F,1,NaN,NaN,NaN,0.97266,2.037585,94.46703,209.488250,228.407
2,S100,Cohort2,BPTB,51,M,1,NaN,NaN,7.0,0.78039,0.145589,102.36600,461.141000,NaN
3,S101,Cohort2,BPTB,61,M,1,NaN,NaN,8.0,0.70122,0.002805,60.57900,142.950000,NaN
4,S102,Cohort2,BPTB,62,M,1,NaN,NaN,9.0,0.21489,0.000860,65.54000,41.088000,NaN

Note that some columns have NaN values, so the easiest step is to delete the columns

Create a copy of the original in-case mistakes are made or the full dataset is needed

In [23]:
cancer_df = kaggle.copy()
cancer_df

,sample_id,patient_cohort,sample_origin,age,sex,diagnosis,stage,benign_sample_diagnosis,plasma_CA19_9,creatinine,LYVE1,REG1B,TFF1,REG1A
0,S1,Cohort1,BPTB,33,F,1,NaN,NaN,11.7,1.83222,0.893219,52.948840,654.282174,1262.000
1,S10,Cohort1,BPTB,81,F,1,NaN,NaN,NaN,0.97266,2.037585,94.467030,209.488250,228.407
2,S100,Cohort2,BPTB,51,M,1,NaN,NaN,7.0,0.78039,0.145589,102.366000,461.141000,NaN
3,S101,Cohort2,BPTB,61,M,1,NaN,NaN,8.0,0.70122,0.002805,60.579000,142.950000,NaN
4,S102,Cohort2,BPTB,62,M,1,NaN,NaN,9.0,0.21489,0.000860,65.540000,41.088000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,S549,Cohort2,BPTB,68,M,3,IV,NaN,NaN,0.52026,7.058209,156.241000,525.178000,NaN
586,S558,Cohort2,BPTB,71,F,3,IV,NaN,NaN,0.85956,8.341207,16.915000,245.947000,NaN
587,S560,Cohort2,BPTB,63,M,3,IV,NaN,NaN,1.36851,7.674707,289.701000,537.286000,NaN
588,S583,Cohort2,BPTB,75,F,3,IV,NaN,NaN,1.33458,8.206777,205.930000,722.523000,NaN
589,S590,Cohort1,BPTB,74,M,3,IV,NaN,1488.0,1.50423,8.200958,411.938275,2021.321078,13200.000

In [24]:
cancer_df.isnull().sum()

sample_id                    0
patient_cohort               0
sample_origin                0
age                          0
sex                          0
diagnosis                    0
stage                      391
benign_sample_diagnosis    382
plasma_CA19_9              240
creatinine                   0
LYVE1                        0
REG1B                        0
TFF1                         0
REG1A                      284
dtype: int64

In [25]:
import numpy as np
for column in cancer_df:
    print('{} has {} % missing values'.format(column,np.round(cancer_df[column].isnull().sum()/len(cancer_df)*100,2)))

sample_id has 0.0 % missing values
patient_cohort has 0.0 % missing values
sample_origin has 0.0 % missing values
age has 0.0 % missing values
sex has 0.0 % missing values
diagnosis has 0.0 % missing values
stage has 66.27 % missing values
benign_sample_diagnosis has 64.75 % missing values
plasma_CA19_9 has 40.68 % missing values
creatinine has 0.0 % missing values
LYVE1 has 0.0 % missing values
REG1B has 0.0 % missing values
TFF1 has 0.0 % missing values
REG1A has 48.14 % missing values

Dropping any column with a NaN value is easy, but more than likely going to alter the integrity of the data

In [26]:
cancer_df.dropna(how = "any", axis = 1)

,sample_id,patient_cohort,sample_origin,age,sex,diagnosis,creatinine,LYVE1,REG1B,TFF1
0,S1,Cohort1,BPTB,33,F,1,1.83222,0.893219,52.948840,654.282174
1,S10,Cohort1,BPTB,81,F,1,0.97266,2.037585,94.467030,209.488250
2,S100,Cohort2,BPTB,51,M,1,0.78039,0.145589,102.366000,461.141000
3,S101,Cohort2,BPTB,61,M,1,0.70122,0.002805,60.579000,142.950000
4,S102,Cohort2,BPTB,62,M,1,0.21489,0.000860,65.540000,41.088000
...,...,...,...,...,...,...,...,...,...,...
585,S549,Cohort2,BPTB,68,M,3,0.52026,7.058209,156.241000,525.178000
586,S558,Cohort2,BPTB,71,F,3,0.85956,8.341207,16.915000,245.947000
587,S560,Cohort2,BPTB,63,M,3,1.36851,7.674707,289.701000,537.286000
588,S583,Cohort2,BPTB,75,F,3,1.33458,8.206777,205.930000,722.523000
589,S590,Cohort1,BPTB,74,M,3,1.50423,8.200958,411.938275,2021.321078

Create dropped_df with the original copy we kept

In [27]:
cancer_df = cancer_df.copy()

I selected columns in which thousands of values are missing, as filling those in with the mode would skew the results heavily

Manually selecting which columns to drop is generally a better option than configuring some sort of quota for which if statements decide to exclude

In [28]:
cancer_df = cancer_df.drop(['sample_id', 'stage', 'benign_sample_diagnosis'], axis = 1)

In [29]:
cancer_df.mode()

,patient_cohort,sample_origin,age,sex,diagnosis,plasma_CA19_9,creatinine,LYVE1,REG1B,TFF1,REG1A
0,Cohort1,BPTB,68.0,F,2.0,9.0,0.57681,0.000814,1.769536,0.024701,0.0
1,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,2.450000,0.044991,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.099211,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.225890,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.366192,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.232180,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.754893,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.427000,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.969010,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.393900,NaN,NaN

Using the mode of each column, the NaN values are replaced

We check again to see that there are no more null values

In [31]:
cancer_clean_df = cancer_df.copy()
for c in cancer_clean_df.columns:
    cancer_clean_df[c].fillna(cancer_df[c].mode()[0], inplace=True)

cancer_clean_df.isnull().sum()

patient_cohort    0
sample_origin     0
age               0
sex               0
diagnosis         0
plasma_CA19_9     0
creatinine        0
LYVE1             0
REG1B             0
TFF1              0
REG1A             0
dtype: int64

In [32]:
cancer_clean_df

,patient_cohort,sample_origin,age,sex,diagnosis,plasma_CA19_9,creatinine,LYVE1,REG1B,TFF1,REG1A
0,Cohort1,BPTB,33,F,1,11.7,1.83222,0.893219,52.948840,654.282174,1262.000
1,Cohort1,BPTB,81,F,1,9.0,0.97266,2.037585,94.467030,209.488250,228.407
2,Cohort2,BPTB,51,M,1,7.0,0.78039,0.145589,102.366000,461.141000,0.000
3,Cohort2,BPTB,61,M,1,8.0,0.70122,0.002805,60.579000,142.950000,0.000
4,Cohort2,BPTB,62,M,1,9.0,0.21489,0.000860,65.540000,41.088000,0.000
...,...,...,...,...,...,...,...,...,...,...,...
585,Cohort2,BPTB,68,M,3,9.0,0.52026,7.058209,156.241000,525.178000,0.000
586,Cohort2,BPTB,71,F,3,9.0,0.85956,8.341207,16.915000,245.947000,0.000
587,Cohort2,BPTB,63,M,3,9.0,1.36851,7.674707,289.701000,537.286000,0.000
588,Cohort2,BPTB,75,F,3,9.0,1.33458,8.206777,205.930000,722.523000,0.000
589,Cohort1,BPTB,74,M,3,1488.0,1.50423,8.200958,411.938275,2021.321078,13200.000